DefaultContentLanguage = "en"
baseurl = "https://gaysianthirdspace.github.io/"
canonifyurls = true
disqusShortname = ""
languageCode = "en"
metaDataFormat = "toml"
paginate = 10
paginatePath = "page"
theme = "hugo-bootstrap-premium"
[author]
email = "gaysianthirdspace@gmail.com"
name = "Gaysian Third Space"
[blackfriday]
angledQuotes = true
extensionmask = []
extensions = []
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
[[menu.footer]]
identifier = "ig"
name = "Instagram"
pre = "<i>&middot;</i>"
url = "https://www.instagram.com/gaysianthirdspace"
weight = 4
[[menu.footer]]
identifier = "fb"
name = "Facebook"
pre = "<i>&middot;</i>"
url = "https://www.facebook.com/gaysianthirdspace"
weight = 3
[[menu.footer]]
identifier = "tumblr"
name = "Tumblr"
pre = "<i>&middot;</i>"
url = "http://gaysianthirdspace.tumblr.com"
weight = 2
[[menu.footer]]
identifier = "about"
name = "About G3S"
pre = "<i>&middot;</i>"
url = "/about"
weight = 1
[[menu.main]]
identifier = "home"
name = "Home"
pre = ""
url = "/"
weight = 4
[params]
bitbucket = ""
brand = "Gaysian Third Space"
brandimage = "http://res.cloudinary.com/gaysianthirdspace/image/upload/c_scale,h_60/v1505534413/G3S_Logo_Long_for_Dark_Background_ho4zir.png"
customcss = ["/css/style_custom.css"]
customjs = []
facebook = "gaysianthirdspace"
flattr = ""
footline = "Here is a footer!"
github = ""
googleanalytics = "UA-77731767-1"
googleplus = ""
highlight = "default"
home = "Home"
instagram = "gaysianthirdspace"
linkedin = ""
mailmunchid = ""
mathjax = "2.7.1"
showrightsidebar = false
sumomeid = ""
switchlang = false
topline = "Outside of the apps and the clubs/raves, we seek to create a Third Space for individuals to find support and community as each of us navigate our gay(sian) experience. Get involved in our community and make some new friends!"
tumblr = "gaysianthirdspace"
twitter = ""
youtube = ""
[params.popover]
cookiename = "mycookie1"
enablepopover = false
errormessage = "Submitting form failed!"
expirecookie = 5
headerimage = "//placehold.it/1000x600"
imagedescription = "Placeholder image for this popover modal optin form"
inputplaceholder = "Enter your email"
modalsize = ""
mouseleave = true
optin = true
posturl = "https://zapier.com/hooks/catch/1227563/"
showmodaltimeout = 10000
signupheader = "Join Our Newsletter"
signuptext = "Signup today for free and be the first to get notified on new updates."
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
[params.theme]
name = "sandstone"
[permalinks]
code = "/:filename/"
post = "/:year/:month/:day/:filename/"
[taxonomies]
tag = "tags"
topic = "topics"
